open OUnit2
open Days

let test_day07_part1_sample =
  "Day07 Part1 Sample" >:: (fun _ ->
    let sample_input = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............." in
    let result = Day07.Solution.part1 sample_input in
    assert_equal "21" result
  )

let test_day07_part2_sample =
  "Day07 Part2 Sample" >:: (fun _ ->
    let sample_input = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............." in
    let result = Day07.Solution.part2 sample_input in
    assert_equal "40" result
  )

let suite = "Day07 Tests" >::: [
  test_day07_part1_sample;
  test_day07_part2_sample;
]